# Generated by Django 5.2 on 2025-04-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
