# Generated by Django 5.2 on 2025-04-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste full YouTube URL here', null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
